services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev 
    volumes:
      - ./apps/api:/app/apps/api
      - ./packages:/app/packages 
    ports:
      - "8000:8000"
    env_file:
      - ./apps/api/.env
    command: yarn workspace api dev
  
  worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./apps/api:/app/apps/api # Sync API code (worker is inside api)
      - ./packages:/app/packages       # Sync Shared packages
    command: yarn workspace api dev:worker
    env_file:
      - ./apps/api/.env