services:
  api:
    image: styxflow-backend
    build:
      context: .
      dockerfile: Dockerfile.dev 
    volumes:
      - ./apps/api:/app/apps/api
      - ./packages:/app/packages 
    ports:
      - "8000:8000"
    env_file:
      - ./apps/api/.env
    command: yarn workspace api dev
  
  worker:
    image: styxflow-backend
    volumes:
      - ./apps/api:/app/apps/api 
      - ./packages:/app/packages   
    command: yarn workspace api dev:worker
    env_file:
      - ./apps/api/.env
